#!/bin/bash

if [ $# -lt 1 ]; then
   echo "输入md文件"
   exit 1
fi

filename=${1%.*}
echo "filename ：${filename}"
filePath="./posts/${1}"

# 新建文章
cd ../
echo "creating..."
hexo new ${filename}

# 创建md原文档备份
echo "create md back file..."
cp ${filePath} ./posts/${filename}.bak

# 获取标题时间
title=`cat ${filePath} |grep "#" -m 1|awk '{print $2}'`
time=`date +%T`
date=`date +%F`
tags=""
categories=""

# 删除第一个---号之前的所有行
sed -i '1,/---/d' ${filePath}

# 替换第一个## 前面的行里面的---
sed -i '1,/##/s/---/<!--more-->/' ${filePath}

# 添加分类标签
if [ $# -ge 2 ]; then
    categories=${2}
fi
if [ $# -ge 3 ]; then
    tags=${3}
fi

# 替换插入
echo "title: ${title}"
echo "date: ${date} ${time}"
echo "tags: ${tags}"
echo "categories: ${categories}"

sed -i '1i---' ${filePath}
sed -i "1icategories: ${categories}" ${filePath}
sed -i "1itags: ${tags}" ${filePath}
sed -i "1idate: ${date} ${time}" ${filePath}
sed -i "1ititle: ${title}" ${filePath}
sed -i '1i---' ${filePath}

# 去掉行尾的
sed -i 's///' ${filePath}

# 自己的md文件覆盖自动生成的文件
cp ${filePath} ./source/_posts/
